# Generated by Django 2.0.7 on 2018-07-19 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Comércio')),
                ('slug', models.CharField(max_length=100, verbose_name='Identificador')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Comércio',
                'verbose_name_plural': 'Comércios',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Gasto')),
                ('slug', models.CharField(max_length=100, verbose_name='Identificador')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('datagasto', models.DateField(blank=True, default=datetime.datetime.today, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em')),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helloworld.Comercio', verbose_name='Comércio')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-datagasto'],
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
